In [2]:
#Biblioteca para tratar dados, operações com arrays
import numpy as np

In [5]:
#criando um array e verificando o seu tipo
vetor = np.array([12, 34, 26, 18, 10])
print(vetor)
print(type(vetor))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [7]:
#Criando um array com um tipo específico
# array do tipo float de 64bits
vetorFloat = np.array([1, 2, 3], dtype = np.float64)
print(vetorFloat)
print(type(vetorFloat))

#Tipo inteiro 32bits
vetorInt = np.array([1, 2 , 3], dtype = np.int32)
print(vetorInt)
print(type(vetorInt))


[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [8]:
#mudando o tipo de um array
novoVetor = np.array([1.4, 3.6, -5.1, 9.42, 4.9999999])
print(novoVetor)

#float -> int
novoVetorInt = novoVetor.astype(np.int32)
print(novoVetorInt)

[ 1.4        3.6       -5.1        9.42       4.9999999]
[ 1  3 -5  9  4]


In [10]:
#Criando matrizes
#Matriz 3x3
matriz = np.array([[7, 2, 23], [12, 27, 4], [5, 34, 23]])
print(matriz)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [15]:
#Criando arrays vazios tipificados
#empty significa que não são inicializados, não que são vazios. Lixo de memória?
vazio = np.empty([3, 2], dtype = int)
print(vazio)
print("------------")
zeros = np.zeros([4,3]) #4x3
print(zeros)
print("------------")
um = np.ones([5, 7])
print(um)
print("------------")
#Cria uma matriz com a diagonal principal com valores 1 e os outros valores 0
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
#valores aletórios entre 0 e 1
rand = np.random.random((5))
print(rand)
print("------------")
#valores aleatórios distr. normal contendo negativos
rand2 = np.random.randn((5))
print(rand2)
print("------------")
#valores aleatórios 3 x 4
rand3 = (10*np.random.random((3, 4)))
print(rand3)

[0.75954139 0.25022745 0.3419463  0.48261645 0.41250113]
------------
[-1.33258839 -0.90351484 -0.74688238  0.42422508 -1.21769549]
------------
[[4.51590605 8.53498001 9.26473762 2.56890266]
 [6.79750862 8.83105957 9.74506078 0.033013  ]
 [0.47510044 7.39928378 1.27381786 7.33492852]]


In [22]:
#outra forma de gerar aleatórios
#usando semente (seed)
rng = np.random.default_rng(1)
rand4 = rng.random(3)
print(rand4)

#gerando inteiros
rand5 = rng.integers(100, size = (3, 4))
print(rand5)

[0.51182162 0.9504637  0.14415961]
[[82 94 24 31]
 [86 42 27 82]
 [25 40 64 54]]


In [24]:
#unique remove repetições
j = np.array([11, 12, 13, 13, 14, 15, 16, 11, 17, 23, 18, 34, 23, 42])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 23 34 42]


In [27]:
#Acessando posições em matrizes
print(matriz)
print(matriz[0][1])
print(matriz.shape)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]
2
(3, 3)


In [29]:
#Funções matemáticas
# Mostra o maior valor da matriz "matriz"
print(matriz.max())
# Mostra o menor valor da matriz "matriz"
print(matriz.min())
# Mostra a soma dos valores da matriz "matriz"
print(matriz.sum())
# Mostra o valor da média do valores da matriz "matriz"
print(matriz.mean())
# Mostra o valor do desvio padrão (standard deviation) dos valores da matriz "matriz"
print(matriz.std())

34
2
137
15.222222222222221
11.033059188716807


In [31]:
myArray = np.array([1, 2, 9, 7, 5, 3, 4, 22])
# Elemento na posição 1
print(myArray[1])
print("------------")
# Mostra o array criado a partir da posição 0 até o segundo elemento
print(myArray[0:2])
print("------------")
# Da segunda posição para frente
print(myArray[1:])
print("------------")
# Os ultimos 3 elementos
print(myArray[-3:])

2
------------
[1 2]
------------
[ 2  9  7  5  3  4 22]
------------
[ 3  4 22]


In [35]:
#Funções universais, aplicadas a todos os elementos
#Raiz quadrada de todos os elementos
array = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(array))
#Valor exponecial de todos os elementos
print(np.exp(array))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [39]:
#extração de linhas e colunas
matrix = np.array([[4, 5], [6, 1], [7, 4]])
print(matrix)
print("------------")
#Primeira linha
matrixLine1 = matrix[0, :]
print(matrixLine1)
print("------------")
#terceira linha
matrixLine3 = matrix[2, :]
print(matrixLine3)
print("------------")
#Segunda Coluna
matrixColumn2 = matrix[:, 1]
print(matrixColumn2)

[[4 5]
 [6 1]
 [7 4]]
------------
[4 5]
------------
[7 4]
------------
[5 1 4]


In [ ]:
#Transposição
myMatrix = np.arange(15).reshape(3, 5)
print(myMatrix)
print("------------")
matrixT = myMatrix.T
print(matrixT)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [51]:
#expressões lógicas
#usando where
v = np.random.randn(4, 4)
print(v)
x = (v > 0)
print(x)
z = np.where(x > 0, 1, -1)
print(z)

[[ 0.3447487  -0.2528282  -0.45560182  0.12704308]
 [ 0.92835637  0.08674368 -1.04159194  1.42076368]
 [ 0.71887809  0.20481903  0.66061338  0.04951569]
 [-1.38502582  1.23281055  0.6485414   0.15746593]]
[[ True False False  True]
 [ True  True False  True]
 [ True  True  True  True]
 [False  True  True  True]]
[[ 1 -1 -1  1]
 [ 1  1 -1  1]
 [ 1  1  1  1]
 [-1  1  1  1]]
